### ISSUE TITLE
Add new endpoint for locking

### ISSUE THREAD

**Issue by parberge** [codelabsab/timereport-api#13]
To support sign-off/approve/lock of a timereport we want to create a new endpoint
PUT /event/users/{user_id} with params:
* locked=`bool`
* date=`date as string`

It should iterate over the time range and update the key in the document used for locking (presumably "locked")

**Comment by kamigerami** [comment]
<img width="1267" alt="Screenshot 2019-06-01 at 11 01 16" src="https://user-images.githubusercontent.com/9321510/58746268-ba5c9c80-845c-11e9-8533-3718346e4232.png">

This will add a new item to the table called "lock" and is of type BooleanAttribute and defaults to False on everything that gets created. 

Later when we implement sign-off we can easily "update" this table to True and also add our checks before we delete or put anything to any events

**Comment by kamigerami** [comment]
we should look into this:
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb.html#DynamoDB.Client.put_item

**Comment by parberge** [comment]
So for clarity: We decided to only update the event that we insert to the DB to include the lock attribute.

The logic for locking, unlocking, and to honor locked events will need to be added in every client instead.
