### ISSUE TITLE
dev backend returns list instead of dict for api/event/users

### ISSUE THREAD

**Issue by kamigerami** [codelabsab/timereport-api#23]
When querying {backend_url}/event/users using dev we will get back:

dev: ["U2FG26ZFF", "fake", "U2FGC795G", "U86BEEK5W"]

prod: {"kamger":"U2FGC795G","par.berge":"U86BEEK5W","mauricio.saez":"UKBV2G2A2"}

thus giving us wrong data in for example timereport-UI.  (index vs actual usernames)

See examples from timereport-UI in dev / prod below 

<img width="834" alt="Screen Shot 2019-10-20 at 00 07 46" src="https://user-images.githubusercontent.com/9321510/67152047-c643e080-f2cf-11e9-9cba-0e824bbc69bd.png">
<img width="1087" alt="Screen Shot 2019-10-20 at 00 03 03" src="https://user-images.githubusercontent.com/9321510/67152048-c6dc7700-f2cf-11e9-9eba-143221c405df.png">

**Comment by parberge** [comment]
I believe this issue is no longer a problem.

The `/event/users` endpoint is old and when this PR is merged https://github.com/codelabsab/timereport-ui/pull/19 it should be removed.

**Comment by tommymalmqvist** [comment]
Closing
