### ISSUE TITLE
Add get_users api endpoint

### ISSUE THREAD

**Issue by kamigerami** [codelabsab/timereport-api#3]
so we can get a list of all users (required for frontend functionality)

**Comment by parberge** [comment]
Isn't this provided by `/user/names` endpoint?

**Comment by parberge** [comment]
Since we have updated the API since this ticket is created, the endpoint that returns all users has changed to:
`/event/users`

I think this ticket should be closed @kamigerami

**Comment by tommymalmqvist** [comment]
This has been added in [refactor-pynamodb app.py](https://github.com/codelabsab/timereport-api/blob/refactor-pynamodb/app.py#L31)

**Comment by parberge** [comment]
@kamigerami This is possible with the this route:
https://github.com/codelabsab/timereport-api/blob/f0b0cee6c281648811f2f2ffb71a35eab9ee466c/app.py#L216
